### ISSUE TITLE
Add paragraph rendering

### ISSUE THREAD

**Issue by vernrwalker** [SteveStrongBAH/legalmarker#15]
Only on "All" mode of display in Marker

**Comment by SteveStrongBAH** [comment]
Mic Drop,  we render paragraphs

<img width="921" alt="Screen Shot 2019-05-15 at 9 46 17 PM" src="https://user-images.githubusercontent.com/19686538/57820465-eab4f300-775a-11e9-9f8f-1db38cca0a10.png">
